export const acts = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USER: 'FETCH_USER',
  SHOW_PRELOADER: 'SHOW_PRELOADER',
  HIDE_PRELOADER: 'HIDE_PRELOADER',
  SET_SELECTED_PAGE: 'SET_SELECTED_PAGE',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
};
